title: Sanjna Suresh
email: sanjnasuresh@umass.edu
description: Personal website for research, projects, and resume
baseurl: ""
url: "https://sanjna10.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag